refs #36863 : add logo to card payment radio in checkout page
202-ecommerce/stripe_official pull request #190
Opened 2022-11-14 11:28 UTC by Afayadas

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add logo to card payment method in checkout page
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Evol #36863
| How to test?  | Go to checkout page in payment method step

2022-11-14 14:19 UTC, clotairer commented
Please fix php cs fixer

2022-11-14 14:21 UTC, clotairer approved these changes

2022-11-14 14:22 UTC, clotairer requested changes

2022-11-14 14:22 UTC, clotairer commented on stripe_official.php
> +                ->setLogo(Media::getMediaPath(_PS_MODULE_DIR_.$this->name.'/views/img/'.$cc_img))
phpcs fix down

2022-11-15 07:52 UTC, clotairer approved these changes

2022-11-15 10:38 UTC, merged

2022-12-02 10:37 UTC, HartLarsson commented
the first icon what is? a credit card?
why not use a icon that is more redable?

![logo_all_card_payment](https://user-images.githubusercontent.com/16102074/205274106-1f4ff975-5204-483b-9dcd-1055f28f4b37.png)
![logo_card_payment](https://user-images.githubusercontent.com/16102074/205274111-204d056a-4146-4aa0-aa1f-1239af3bc019.png)